### ISSUE TITLE
Inquiry About Open Source Plans

### ISSUE THREAD

**Issue by luo0207** [mega-sam/mega-sam#1]
We are looking to implement our content based on your algorithm and would greatly appreciate any information regarding an estimated timeline for when it might be available.

**Comment by zjwzcx** [comment]
Same. 
Awesome work!!

**Comment by yzhang4179** [comment]
Nice work!! When can we expect a full open-sourced project? Thanks a lot!

**Comment by holynski** [comment]
The code itself is ready for release but is going through internal review procedures, so I can't give you an exact timeline, sorry!

If you need a sequence or two processed for a submission imminently, I'd be happy to run it for you. 

Best,
Aleks
