### ISSUE TITLE
Release MegaSAM on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [mega-sam/mega-sam#2]
Hello @jinlinyi  🤗

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work on Twitter, and indexed the paper page here: https://huggingface.co/papers/2412.04463. The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance), you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the model you've pre-trained on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a custom PyTorch model, you can use the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to the model which lets you to upload the model and people to download and use models right away. If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).\n\nAfter uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

You can also build a demo for your model on [Spaces](https://huggingface.co/spaces), we can provide you an A100 grant.\n\nWhat do you think?

Let me know if you're interested/need any guidance.

Kind regards,

Niels

**Comment by holynski** [comment]
Thanks for the guide. We'll keep it in mind.

**Comment by NielsRogge** [comment]
Thanks for your reply, would it be possible to keep the issue open so that we can track it?

**Comment by holynski** [comment]
I would encourage you to track this issue elsewhere. We plan to deprecate this repository (as the official release will likely be hosted elsewhere).

**Comment by NielsRogge** [comment]
Ok cool, once there's a release, feel free to let us know!
